"""Package jupyterlab-ghmath as a prebuilt JupyterLab extension."""

from pathlib import Path

from setuptools import setup

# PACKAGE_NAME is the Python distribution and labextension directory name.
PACKAGE_NAME = "jupyterlab-ghmath"

# HERE is the repository root used to resolve generated labextension assets.
HERE = Path(__file__).parent

# LABEXTENSION_DIR is generated by `npm run build:labextension`.
LABEXTENSION_DIR = HERE / "jupyterlab_ghmath" / "labextension"


def labextension_data_files() -> list[tuple[str, list[str]]]:
    """Return wheel data_files entries for files under LABEXTENSION_DIR."""
    data_files: dict[str, list[str]] = {}

    for path in LABEXTENSION_DIR.rglob("*"):
        if not path.is_file():
            continue
        relative_parent = path.relative_to(LABEXTENSION_DIR).parent
        target = Path("share") / "jupyter" / "labextensions" / PACKAGE_NAME
        if str(relative_parent) != ".":
            target = target / relative_parent
        source = path.relative_to(HERE)
        data_files.setdefault(str(target), []).append(source.as_posix())

    return sorted((target, sorted(paths)) for target, paths in data_files.items())


setup(data_files=labextension_data_files())
